# $File: //ASP/tec/epics/asubExec/trunk/asubExecTestApp/Db/Makefile $
# $Revision: #1 $
# $DateTime: 2018/11/03 17:51:37 $
# Last checked in by: $Author: starritt $
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB += example.db
DB += mid_points.db

SCRIPTS += example.py
SCRIPTS += mid_points.py

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


# end
